<?php

namespace Database\Factories;

use App\Models\User;
use App\Models\Stations;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Stations>
 */
class StationsFactory extends Factory
{
    protected $model = Stations::class;

    public function definition(): array
    {

        $regions = [
            'Dolnośląskie' => [
                'bolesławiecki' => 'bolesławiecki',
                'dzierżoniowski' => 'dzierżoniowski',
                'głogowski' => 'głogowski',
                'jeleniogórski' => 'jeleniogórski',
                'kamiennogórski' => 'kamiennogórski',
                'kłodzki' => 'kłodzki',
                'legnicki' => 'legnicki',
                'lubański' => 'lubański',
                'lwówecki' => 'lwówecki',
                'milicki' => 'milicki',
                'oleśnicki' => 'oleśnicki',
                'oławski' => 'oławski',
                'polkowicki' => 'polkowicki',
                'strzeliński' => 'strzeliński',
                'świdnicki' => 'świdnicki',
                'trzebnicki' => 'trzebnicki',
                'wałbrzyski' => 'wałbrzyski',
                'wołowski' => 'wołowski',
                'wrocławski' => 'wrocławski',
                'zgorzelecki' => 'zgorzelecki',
                'złotoryjski' => 'złotoryjski',
                'Jelenia Góra' => 'Jelenia Góra',
                'Legnica' => 'Legnica',
                'Wałbrzych' => 'Wałbrzych',
                'Wrocław' => 'Wrocław',
            ],
            'Kujawsko-pomorskie' => [
                'brodnicki' => 'brodnicki',
                'bydgoski' => 'bydgoski',
                'chełmiński' => 'chełmiński',
                'golubsko-dobrzyński' => 'golubsko-dobrzyński',
                'grudziądzki' => 'grudziądzki',
                'inowrocławski' => 'inowrocławski',
                'lipnowski' => 'lipnowski',
                'mogileński' => 'mogileński',
                'nakielski' => 'nakielski',
                'radziejowski' => 'radziejowski',
                'rypiński' => 'rypiński',
                'sępoleński' => 'sępoleński',
                'świecki' => 'świecki',
                'toruński' => 'toruński',
                'tucholski' => 'tucholski',
                'wąbrzeski' => 'wąbrzeski',
                'węgorzewski' => 'węgorzewski',
                'żniński' => 'żniński',
                'Bydgoszcz' => 'Bydgoszcz',
                'Grudziądz' => 'Grudziądz',
                'Toruń' => 'Toruń',
            ],
            'Lubelskie' => [
                'bialski' => 'bialski',
                'biłgorajski' => 'biłgorajski',
                'chełmski' => 'chełmski',
                'hrubieszowski' => 'hrubieszowski',
                'janowski' => 'janowski',
                'krasnostawski' => 'krasnostawski',
                'kraśnicki' => 'kraśnicki',
                'lubartowski' => 'lubartowski',
                'lubelski' => 'lubelski',
                'łukowski' => 'łukowski',
                'parczewski' => 'parczewski',
                'puławski' => 'puławski',
                'radzyński' => 'radzyński',
                'rycki' => 'rycki',
                'tomaszowski' => 'tomaszowski',
                'włodawski' => 'włodawski',
                'zamojski' => 'zamojski',
                'Biała Podlaska' => 'Biała Podlaska',
                'Chełm' => 'Chełm',
                'Lublin' => 'Lublin',
                'Zamość' => 'Zamość',
            ],
            'Lubuskie' => [
                'gorzowski' => 'gorzowski',
                'krośnieński' => 'krośnieński',
                'międzyrzecki' => 'międzyrzecki',
                'nowosolski' => 'nowosolski',
                'sulęciński' => 'sulęciński',
                'słubicki' => 'słubicki',
                'zielonogórski' => 'zielonogórski',
                'żarski' => 'żarski',
                'Gorzów Wielkopolski' => 'Gorzów Wielkopolski',
                'Zielona Góra' => 'Zielona Góra',
            ],
            'Łódzkie' => [
                'bełchatowski' => 'bełchatowski',
                'brzeziński' => 'brzeziński',
                'kutnowski' => 'kutnowski',
                'łowicki' => 'łowicki',
                'łódzki wschodni' => 'łódzki wschodni',
                'łódzki zachodni' => 'łódzki zachodni',
                'piotrkowski' => 'piotrkowski',
                'pabianicki' => 'pabianicki',
                'pajęczański' => 'pajęczański',
                'radomszczański' => 'radomszczański',
                'sieradzki' => 'sieradzki',
                'skierniewicki' => 'skierniewicki',
                'tomaszowski' => 'tomaszowski',
                'wieluński' => 'wieluński',
                'wieruszowski' => 'wieruszowski',
                'zduńskowolski' => 'zduńskowolski',
                'zgierski' => 'zgierski',
                'Łódź' => 'Łódź',
                'Piotrków Trybunalski' => 'Piotrków Trybunalski',
                'Skierniewice' => 'Skierniewice',
            ],
            'Małopolskie' => [
                'bocheński' => 'bocheński',
                'brzeski' => 'brzeski',
                'chrzanowski' => 'chrzanowski',
                'dąbrowski' => 'dąbrowski',
                'gorlicki' => 'gorlicki',
                'krakowski' => 'krakowski',
                'limanowski' => 'limanowski',
                'miechowski' => 'miechowski',
                'nowosądecki' => 'nowosądecki',
                'nowotarski' => 'nowotarski',
                'olkuski' => 'olkuski',
                'oświęcimski' => 'oświęcimski',
                'proszowicki' => 'proszowicki',
                'suski' => 'suski',
                'tarnowski' => 'tarnowski',
                'wadowicki' => 'wadowicki',
                'wielicki' => 'wielicki',
                'Bożec' => 'Bożec',
                'Kielce' => 'Kielce',
                'Kraków' => 'Kraków',
                'Nowy Sącz' => 'Nowy Sącz',
                'Tarnów' => 'Tarnów',
            ],
            'Mazowieckie' => [
                'bielski' => 'bielski',
                'ciechanowski' => 'ciechanowski',
                'garwoliński' => 'garwoliński',
                'gostyniński' => 'gostyniński',
                'grodziski' => 'grodziski',
                'grójecki' => 'grójecki',
                'kozienicki' => 'kozienicki',
                'legionowski' => 'legionowski',
                'lipski' => 'lipski',
                'łowicki' => 'łowicki',
                'makowski' => 'makowski',
                'międzyrzecki' => 'międzyrzecki',
                'ostrołęcki' => 'ostrołęcki',
                'ostrowski' => 'ostrowski',
                'ostrowiecki' => 'ostrowiecki',
                'piaseczyński' => 'piaseczyński',
                'płocki' => 'płocki',
                'pruszkowski' => 'pruszkowski',
                'pruszków' => 'pruszków',
                'radomski' => 'radomski',
                'siedlecki' => 'siedlecki',
                'sierpecki' => 'sierpecki',
                'sochaczewski' => 'sochaczewski',
                'szydłowiecki' => 'szydłowiecki',
                'warszawski zachodni' => 'warszawski zachodni',
                'wołomiński' => 'wołomiński',
                'węgrowski' => 'węgrowski',
                'żyrardowski' => 'żyrardowski',
                'Ostrołęka' => 'Ostrołęka',
                'Płock' => 'Płock',
                'Radom' => 'Radom',
                'Siedlce' => 'Siedlce',
                'Warszawa' => 'Warszawa',
            ],
            'Opolskie' => [
                'brzeski' => 'brzeski',
                'krapkowicki' => 'krapkowicki',
                'namysłowski' => 'namysłowski',
                'nyski' => 'nyski',
                'opolski' => 'opolski',
                'prudnicki' => 'prudnicki',
                'strzelecki' => 'strzelecki',
                'Opole' => 'Opole',
            ],
            'Podkarpackie' => [
                'bieszczadzki' => 'bieszczadzki',
                'brzozowski' => 'brzozowski',
                'dębicki' => 'dębicki',
                'jarosławski' => 'jarosławski',
                'jasielski' => 'jasielski',
                'kolbuszowski' => 'kolbuszowski',
                'krośnieński' => 'krośnieński',
                'lubaczowski' => 'lubaczowski',
                'leski' => 'leski',
                'mielecki' => 'mielecki',
                'przemyski' => 'przemyski',
                'ropczycko-sędziszowski' => 'ropczycko-sędziszowski',
                'rzeszowski' => 'rzeszowski',
                'sanocki' => 'sanocki',
                'stalowowolski' => 'stalowowolski',
                'strzyżowski' => 'strzyżowski',
                'tarnobrzeski' => 'tarnobrzeski',
                'Krosno' => 'Krosno',
                'Przemyśl' => 'Przemyśl',
                'Rzeszów' => 'Rzeszów',
            ],
            'Podlaskie' => [
                'białostocki' => 'białostocki',
                'bielski' => 'bielski',
                'grajewski' => 'grajewski',
                'hajnowski' => 'hajnowski',
                'kolninski' => 'kolneński',
                'łomżyński' => 'łomżyński',
                'moniecki' => 'moniecki',
                'sejneński' => 'sejneński',
                'siemiatycki' => 'siemiatycki',
                'sokólski' => 'sokólski',
                'wysokomazowiecki' => 'wysokomazowiecki',
                'zambrowski' => 'zambrowski',
                'Białystok' => 'Białystok',
                'Łomża' => 'Łomża',
                'Suwałki' => 'Suwałki',
            ],
            'Pomorskie' => [
                'bytowski' => 'bytowski',
                'człuchowski' => 'człuchowski',
                'gdański' => 'gdański',
                'kartuski' => 'kartuski',
                'kwidzyński' => 'kwidzyński',
                'lęborski' => 'lęborski',
                'malborski' => 'malborski',
                'nowodworski' => 'nowodworski',
                'pucki' => 'pucki',
                'słupski' => 'słupski',
                'starogardzki' => 'starogardzki',
                'sztumski' => 'sztumski',
                'tczewski' => 'tczewski',
                'wejherowski' => 'wejherowski',
                'Gdańsk' => 'Gdańsk',
                'Słupsk' => 'Słupsk',
                'Gdynia' => 'Gdynia',
            ],
            'Śląskie' => [
                'bielski' => 'bielski',
                'będziński' => 'będziński',
                'częstochowski' => 'częstochowski',
                'gliwicki' => 'gliwicki',
                'jastrzębski' => 'jastrzębski',
                'katowicki' => 'katowicki',
                'lubliniecki' => 'lubliniecki',
                'mikołowski' => 'mikołowski',
                'myszkowski' => 'myszkowski',
                'piekarski' => 'piekarski',
                'raciborski' => 'raciborski',
                'rybnicki' => 'rybnicki',
                'skarżyski' => 'skarżyski',
                'tarnogórski' => 'tarnogórski',
                'tarnowski' => 'tarnowski',
                'wodzisławski' => 'wodzisławski',
                'zawierciański' => 'zawierciański',
                'zabrzański' => 'zabrzański',
                'Bielsko-Biała' => 'Bielsko-Biała',
                'Bytom' => 'Bytom',
                'Chorzów' => 'Chorzów',
                'Dąbrowa Górnicza' => 'Dąbrowa Górnicza',
                'Gliwice' => 'Gliwice',
                'Jastrzębie-Zdrój' => 'Jastrzębie-Zdrój',
                'Katowice' => 'Katowice',
                'Mysłowice' => 'Mysłowice',
                'Piekary Śląskie' => 'Piekary Śląskie',
                'Ruda Śląska' => 'Ruda Śląska',
                'Rybnik' => 'Rybnik',
                'Sosnowiec' => 'Sosnowiec',
                'Tychy' => 'Tychy',
                'Wodzisław Śląski' => 'Wodzisław Śląski',
                'Zabrze' => 'Zabrze',
                'Żory' => 'Żory',
                'Zawiercie' => 'Zawiercie',
            ],
            'Świętokrzyskie' => [
                'buski' => 'buski',
                'kazimierski' => 'kazimierski',
                'kielecki' => 'kielecki',
                'opatowski' => 'opatowski',
                'ostrowiecki' => 'ostrowiecki',
                'pińczowski' => 'pińczowski',
                'skarżyski' => 'skarżyski',
                'sandomierski' => 'sandomierski',
                'staszowski' => 'staszowski',
                'włoszczowski' => 'włoszczowski',
                'Kielce' => 'Kielce',
            ],

            'Warmińsko-mazurskie' => [
                'bartoszycki' => 'bartoszycki',
                'braniewski' => 'braniewski',
                'działdowski' => 'działdowski',
                'ełcki' => 'ełcki',
                'ełkowski' => 'ełkowski',
                'giżycki' => 'giżycki',
                'gołdapski' => 'gołdapski',
                'kętrzyński' => 'kętrzyński',
                'lidzbarski' => 'lidzbarski',
                'olecki' => 'olecki',
                'olsztyński' => 'olsztyński',
                'ostródzki' => 'ostródzki',
                'szczycieński' => 'szczycieński',
                'węgorzewski' => 'węgorzewski',
                'Olsztyn' => 'Olsztyn',
                'Elbląg' => 'Elbląg',
            ],
            'Zachodniopomorskie' => [
                'białogardzki' => ' białogardzki',
                'choszczeński' => ' choszczeński',
                'drawski' => ' drawski',
                'goleniowski' => ' goleniowski',
                'gryfiński' => ' gryfiński',
                'gryficki' => ' gryficki',
                'kamieński' => ' kamieński',
                'koszaliński' => ' koszaliński',
                'lęborski' => ' lęborski',
                'łódzki wschodni' => ' łódzki wschodni', // (może być pomyłka, bo to nie w zachodniopomorskim)
                'myśliborski' => ' myśliborski',
                'policki' => ' policki',
                'sławieński' => ' sławieński',
                'stargardzki' => ' stargardzki',
                'świdwiński' => ' świdwiński',
                'wałecki' => ' wałecki',
                'Kołobrzeg' => 'Kołobrzeg',
                'Koszalin' => 'Koszalin',
                'Szczecin' => 'Szczecin',
                'Świnoujście' => 'Świnoujście',
            ],
            'Wielkopolskie' => [
                'chodzieski' => 'chodzieski',
                'czarnkowsko-trzcianecki' => 'czarnkowsko-trzcianecki',
                'gostyński' => 'gostyński',
                'grodziski' => 'grodziski',
                'kaliski' => 'kaliski',
                'koniński' => 'koniński',
                'kościański' => 'kościański',
                'krotoszyński' => 'krotoszyński',
                'kolski' => 'kolski',
                'leszczyński' => 'leszczyński',
                'międzychodzki' => 'międzychodzki',
                'nowotomyski' => 'nowotomyski',
                'obornicki' => 'obornicki',
                'ostrowski' => 'ostrowski',
                'pleszewski' => 'pleszewski',
                'poznański' => 'poznański',
                'rawicki' => 'rawicki',
                'szamotulski' => 'szamotulski',
                'szczecinecki' => 'szczecinecki',
                'średzki' => 'średzki',
                'wolsztyński' => 'wolsztyński',
                'wągrowiecki' => 'wągrowiecki',
                'wielkopolski' => 'wielkopolski',
                'złotowski' => 'złotowski',
                'Kalisz' => 'Kalisz',
                'Konin' => 'Konin',
                'Leszno' => 'Leszno',
                'Poznań' => 'Poznań',
            ]

            // ... your other voivodeships
        ];

        // pick voivodeship and district
        $voivodeship = $this->faker->randomElement(array_keys($regions));
        $district = $this->faker->randomElement($regions[$voivodeship]);

        // prepare photo options (relative to storage or full URL)
        $photos = [
            'stacje/przyklad1.jpg',
            'stacje/przyklad2.jpg',
            'stacje/przyklad3.jpg',
            'stacje/przyklad4.jpg',
        ];

        return [
            'id' => (string) random_int(100000000000, 999999999999),
            'user_id' => User::inRandomOrder()->first()?->id,
            'name' => $this->faker->city . ' Stacja',
            'lat' => $this->faker->latitude(51, 54),
            'lon' => $this->faker->longitude(15, 23),
            'voivodeship' => $voivodeship,
            'district' => $district,

            // random photo
            'photo' => $this->faker->randomElement($photos),

            'description' => $this->faker->sentence(12),
            'temperature' => $this->faker->boolean(90),
            'humidity' => $this->faker->boolean(90),
            'wind' => $this->faker->boolean(90),
            'rain' => $this->faker->boolean(90),
            'active' => $this->faker->boolean(95),
            'public' => $this->faker->boolean(95),
        ];
    }
}
