<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\Api\DataController;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

// Route::get('/cmd', function () {
//     if (request()->get('key') !== 'dominik') {
//         abort(403);
//     }
//     //https://meteosystem.dkonto.pl/api/cmd?key=dominik
//     Artisan::call('app:log-imgw-data');

//     $output = Artisan::output(); // Get the output generated by the command

//     return response(
//         "<pre>Command triggered at " . now() . "\n\n$output</pre>"
//     );
// });

Route::apiResource('data', DataController::class, ['only' => ['store']])->middleware(['auth:sanctum', 'throttle:data-ip']); // max 1 request every 10 minutes
